config/routes.rb
Rails.application.routes.draw do
  default_url_options(host: Rails.application.config.action_mailer.default_url_options[:host], port: Rails.application.config.action_mailer.default_url_options[:port])
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'users', to: redirect('/users/edit')
  
  # Home
  root to: 'posts#timeline'
  get 'timeline/:page', to: 'posts#timeline'
  
  # Search
  get 'search', to: 'search#index'
  get 'search/new', to: 'search#new', as: :new_search
  
  # User info
  get 'u/:username', to: 'users#show', as: :user
  get 'u/:username/followers', to: 'users#followers', as: :followers
  get 'u/:username/following', to: 'users#following', as: :following
  
  # User actions
  post 'u/:username/follow', to: 'users#follow', as: :follow
  delete 'u/:username/follow', to: 'users#unfollow'
  post 'p/:post_id/like', to: 'users#like', as: :like
  delete 'p/:post_id/like', to: 'users#unlike'
  
  # Posts
  resources :posts, only: [:show, :new, :create, :destroy]
  get 'posts', to: redirect('/')
  
  # Static
  get 'about', to: 'static#about'
  
  # Notifications
  resources :notifications, only: [:show, :index]
  
  # Letsencrypt
  get '/.well-known/acme-challenge/:id', to: 'static#letsencrypt'
end

app/views/panels/_footer.html.erb
<aside class="panel footer <%= 'd-none d-lg-block' if defined?(only_sidebar) && only_sidebar == true %>">
  <a href="<%= about_path %>">About</a>
</aside>

app/views/panels/_profile.html.erb
<div class="panel profile">
  
  <% if user.profile_picture.attached? && user.profile_picture.variable? %>
    <%= image_tag(user.squared_profile_picture(120), class: "rounded mx-auto d-block") %>
  <% end %>
  
  <div class="display-name"><%= user.display_name %></div>
  <div class="username">@<%= user.username %></div>
  <div class="row">
    <a href="<%= user_path(user.username) %>" class="col">
      <div>Posts</div>
      <div class="count"><%= user.posts_count %></div>
    </a>
    <a href="<%= following_path(user.username) %>" class="col">
        <div>Following</div>
        <div class="count"><%= user.following_count %></div>
    </a>
    <a href="<%= followers_path(user.username) %>" class="col">
      <div>Followers</div>
      <div class="count"><%= user.followers_count %></div>
    </a>
  </div>
  <% if current_user && user != current_user %>
    <% if !current_user.follow?(user) %>
      <%= link_to "Follow", follow_path(username: user.username), method: "post", remote: true, class: "btn btn-outline-primary" %>
    <% else%>
      <%= link_to "Following", follow_path(username: user.username), method: "delete", remote: true, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>