config/routes.rb
Rails.application.routes.draw do
  default_url_options(host: Rails.application.config.action_mailer.default_url_options[:host], port: Rails.application.config.action_mailer.default_url_options[:port])
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'users', to: redirect('/users/edit')
  
  # Home
  root to: 'posts#timeline'
  get 'timeline/:page', to: 'posts#timeline'
  
  # Search
  get 'search', to: 'search#index'
  get 'search/new', to: 'search#new', as: :new_search
  
  # User info
  get 'u/:username', to: 'users#show', as: :user
  get 'u/:username/followers', to: 'users#followers', as: :followers
  get 'u/:username/following', to: 'users#following', as: :following
  
  # User actions
  post 'u/:username/follow', to: 'users#follow', as: :follow
  delete 'u/:username/follow', to: 'users#unfollow'
  post 'p/:post_id/like', to: 'users#like', as: :like
  delete 'p/:post_id/like', to: 'users#unlike'
  
  # Posts
  resources :posts, only: [:show, :new, :create, :destroy]
  get 'posts', to: redirect('/')
  
  # Static
  get 'about', to: 'static#about'
  
  # Notifications
  resources :notifications, only: [:show, :index]
  
  # Letsencrypt
  get '/.well-known/acme-challenge/:id', to: 'static#letsencrypt'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :primary_item, polymorphic: true, optional: true
  belongs_to :secondary_item, polymorphic: true, optional: true
  
  after_commit :update_unread_count, on: [:create, :update, :destroy]
  
  def update_unread_count
    return if self.user.nil?
    self.user.unread_notifications_count = self.user.notifications.where(read_at: nil).count
    self.user.save
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  
  def index
    @notifications = current_user.notifications.order('created_at DESC').page(params[:page]).per(25)
  end
  
  def show
    @notification = current_user.notifications.find(params[:id])
    @notification.read_at = Time.now
    @notification.save
    
    case @notification.notification_type.to_sym
    when :followed, :followed_back
      redirect_to user_path(@notification.primary_item.username)
    when :replied, :reposted, :liked, :mentioned
      redirect_to post_path(@notification.primary_item)
    else
      redirect_to root_path, flash: { error: "Notification not found." }
    end
  end
end

app/views/notifications/_notification_row.html.erb
<div class="notification-row <%= 'bg-dark' unless notification.read_at.nil? %>" data-target="<%= notification_path(notification) %>">
  <%= notification.message.html_safe %><br>
  <small><em><%= time_ago_in_words notification.created_at %> ago</em></small>
</div>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-lg-1">
    <%= render partial: "panels/profile", locals: { user: current_user } %>
    <%= render partial: "panels/footer", locals: { only_sidebar: true } %>
  </div>
  <div class="col-lg-2">
    <div class="panel timeline no-padding">
      <h1>Notifications</h1>
      <%= render partial: "notification_row", collection: @notifications, as: :notification %>
    </div>
  </div>
</div>