config/routes.rb
Rails.application.routes.draw do
  default_url_options(host: Rails.application.config.action_mailer.default_url_options[:host], port: Rails.application.config.action_mailer.default_url_options[:port])
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  get 'users', to: redirect('/users/edit')
  
  # Home
  root to: 'posts#timeline'
  get 'timeline/:page', to: 'posts#timeline'
  
  # Search
  get 'search', to: 'search#index'
  get 'search/new', to: 'search#new', as: :new_search
  
  # User info
  get 'u/:username', to: 'users#show', as: :user
  get 'u/:username/followers', to: 'users#followers', as: :followers
  get 'u/:username/following', to: 'users#following', as: :following
  
  # User actions
  post 'u/:username/follow', to: 'users#follow', as: :follow
  delete 'u/:username/follow', to: 'users#unfollow'
  post 'p/:post_id/like', to: 'users#like', as: :like
  delete 'p/:post_id/like', to: 'users#unlike'
  
  # Posts
  resources :posts, only: [:show, :new, :create, :destroy]
  get 'posts', to: redirect('/')
  
  # Static
  get 'about', to: 'static#about'
  
  # Notifications
  resources :notifications, only: [:show, :index]
  
  # Letsencrypt
  get '/.well-known/acme-challenge/:id', to: 'static#letsencrypt'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  
  before_action :change_default_username
  
  def change_default_username
    if current_user && current_user.is_default_username? && (params[:controller] != "registrations" && params[:action] != "edit" && params[:controller] !~ /devise/)
      redirect_to edit_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info alert-dismissible fade show"
      when :success then "alert alert-success alert-dismissible fade show"
      when :error then "alert alert-danger alert-dismissible fade show"
      when :alert then "alert alert-warning alert-dismissible fade show"
      else "alert alert-secondary alert-dismissible fade show"
    end
  end
end

app/views/application/_flash_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-secondary sticky-top">
  <div class="container">
    <a class="navbar-brand d-none d-md-block d-lg-none" href="<%= root_url %>"><span class="solfanto-brackets">{</span> <span class="solfanto-sublogo">microblog</span> <span class="solfanto-brackets">}</span></a>
    <a class="navbar-brand d-md-none d-lg-block" href="<%= root_url %>"><span class="solfanto-brackets">{</span> <span class="solfanto-logo">Solfanto</span>&nbsp;<span class="solfanto-sublogo">microblog</span> <span class="solfanto-brackets">}</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_user %>
        <li class="nav-item <%= 'active' if controller.action_name == "timeline" %> d-none d-md-block d-lg-none">
          <a class="nav-link" href="<%= root_path %>"><%= icon("fas", "home") %></a>
        </li>
        <li class="nav-item <%= 'active' if controller.action_name == "timeline" %> d-md-none d-lg-block">
          <a class="nav-link" href="<%= root_path %>"><%= icon("fas", "home") %> Home</a>
        </li>
        <li class="nav-item <%= 'active' if controller.controller_name == "notifications" %> d-none d-md-block d-lg-none">
          <a class="nav-link" href="<%= notifications_path %>"><%= icon("far", "bell") %></a>
        </li>
        <li class="nav-item <%= 'active' if controller.controller_name == "notifications" %> d-md-none d-lg-block">
          <a class="nav-link" href="<%= notifications_path %>">
            <%= icon("far", "bell") %> Notifications
            <% if current_user.unread_notifications_count > 0 %>
            <span class="badge badge-primary"><%= current_user.unread_notifications_count %></span>
            <% end %>
          </a>
        </li>
        <!-- <li class="nav-item d-none d-md-block d-lg-none">
          <a class="nav-link" href="#"><%= icon("far", "envelope") %></a>
        </li> -->
        <!-- <li class="nav-item d-md-none d-lg-block">
          <a class="nav-link" href="#"><%= icon("far", "envelope") %> Messages</a>
        </li> -->
        <% end %>
      </ul>
      
      <ul class="navbar-nav">
        <% unless controller.controller_name == "search" && controller.action_name == "new" %>
        <li class="nav-item">
          <form action="<%= search_path %>" method="get" accept-charset="UTF-8" class="form-inline my-2 my-md-0 input-group mb-3" role="search">
            <input name="q" class="form-control" type="search" placeholder="Search" aria-label="Search" aria-describedby="search-button-addon" value="<%= params[:q] %>">
            <div class="input-group-append">
              <button class="btn btn-primary" id="search-button-addon" type="submit"><%= icon("fas", "search") %></button>
            </div>
          </form>
        </li>
        <% end %>
        <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle ml-2 mr-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Me
          </a>
          <div class="dropdown-menu dropdown-menu-right bg-secondary" aria-labelledby="navbarDropdown">
            <a class="dropdown-item text-white" href="<%= edit_user_registration_path %>">Profile</a>
            <div class="dropdown-divider"></div>
            <span class="dropdown-item text-light disabled">Settings</span>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item text-white" %>
          </div>
        </li>
        <li class="nav-item">
          <a class="btn btn-primary" href="<%= new_post_path %>">New</a>
        </li>
        <% else %>
        <li class="nav-item">
          &nbsp;&nbsp;<a class="btn btn-primary" href="<%= new_user_session_path %>">Log in</a>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_new_post_form.html.erb
<%= form_for @new_post do |f| %>
  <% if @new_post.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <ul>
      <% @new_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "What's up?", required: true, autofocus: (controller.controller_name == "posts" && controller.action_name == "new") %>
  </div>
  <div class="form-group d-flex justify-content-between">
    <div class="inputfile-group">
      <%= f.file_field :attachments, multiple: true, direct_upload: true, class: "inputfile", 'data-multiple-caption' => "{count} files selected" %>
      <label for="post_attachments" class="btn btn-outline-primary"><span>Add picture</span></label>
    </div>

    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/application/_post_row.html.erb
<% options = (post.original_post_id && post.original_user_id || post.replies.count > 0) ? { 'data-action' => 'openThread', 'data-target' => '#threadModal', 'data-json' => "#thread-for-post-#{post.id}" } : {} %>
<%= content_tag(:div, options.merge(class: 'post-row', id: "post-row-#{post.id}")) do %>
  <div class="post-body">
    <div class="user">
      <% if post.repost && post.content.blank? %>
      <a href="<%= user_path(username: post.original_user.username) %>">
        <% if post.original_user&.profile_picture&.attached? && post.original_user&.profile_picture&.variable? %>
          <%= image_tag(post.original_user.squared_profile_picture(50), class: "profile-picture") %>
        <% else %>
          <div class="profile-picture"></div>
        <% end %>
        <span class="display-name"><%= post.original_user.display_name %></span>
        <small class="username">@<%= post.original_user.username %></small>
      </a>
      <% else %>
      <a href="<%= user_path(username: post.username) %>">
        <% if post.user&.profile_picture&.attached? && post.user&.profile_picture&.variable? %>
          <%= image_tag(post.user.squared_profile_picture(50), class: "profile-picture") %>
        <% else %>
          <div class="profile-picture"></div>
        <% end %>
        <span class="display-name"><%= post.display_name %></span>
        <small class="username">@<%= post.username %></small>
      </a>
      <% end %>
      <small>
        &middot;
        <a href="<%= post_path(post) %>" class="created-at"><%= time_ago_in_words post.created_at %> ago</a>
      </small>
    </div>
    <% if post.original_post_id && post.original_user_id && !post.repost %>
      <div class="text-muted"><em>Replying to @<%= post.original_user.username %></em></div>
    <% end %>
    <script id="thread-for-post-<%= post.id %>" class="json-data" type="application/json">
      <%= post.full_thread.to_json.html_safe %>
    </script>
    <% if !post.content.blank? %>
    <%= simple_format(html_escape(post.content).gsub(/\@([a-zA-Z0-9_]+)/, '<a href="/u/\1">@\1</a>'), class: "content") %>
    <% elsif post.repost && post.content.blank? %>
    <%= simple_format(html_escape(post.original_post.content).gsub(/\@([a-zA-Z0-9_]+)/, '<a href="/u/\1">@\1</a>'), class: "content") %>
    <div class="text-muted"><em>Reposted by @<%= post.username %></em></div>
    <% end %>
    <% if post.repost && !post.content.blank? %>
    <blockquote class="blockquote panel">
      <%= simple_format(html_escape(post.original_post.content).gsub(/\@([a-zA-Z0-9_]+)/, '<a href="/u/\1">@\1</a>'), class: "mb-0") %>
      <footer class="blockquote-footer"><%= post.original_user.display_name %></footer>
    </blockquote>
    <% end %>
    <% unless post.attachments.empty? %>
      <div class="attachments">
        <% post.attachments.each do |i| %>
          <% if i.previewable? %>
            <%= link_to(image_tag(i.preview(resize: "200x200>")), url_for(i), target: "_blank") %>
          <% elsif i.variable? %>
            <%= link_to(image_tag(i.variant(resize: "200x200")), url_for(i), target: "_blank") %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="reactions">
      <% if post.likes_count > 0 %>
      <div><em>This post got liked by <%= pluralize(post.likes_count, 'person') %>.</em></div>
      <% end %>
      <% if post.reposts_count > 0 %>
      <div><em>This post got reposted by <%= pluralize(post.likes_count, 'person') %>.</em></div>
      <% end %>
    </div>
    <div class="actions">
      <a href="javascript:;" data-action="reply" data-json="#thread-for-post-<%= post.id %>" rel="nofollow"><%= icon("fas", "comment") %> Reply</a>
      <% unless post.user_id == current_user&.id || (post.repost? && post.original_user_id == current_user&.id) %><a href="javascript:;" data-action="repost" data-json="#thread-for-post-<%= post.id %>" rel="nofollow"><%= icon("fas", "retweet") %> Repost</a><% end %>
      <% if current_user&.like?(post.id) %>
      <a href="<%= like_path(post.id) %>" data-method="delete" rel="nofollow" data-remote="true"><%= icon("fas", "heart") %> Like</a>
      <% else %>
      <a href="<%= like_path(post.id) %>" data-method="post" rel="nofollow" data-remote="true"><%= icon("far", "heart") %> Like</a>
      <% end %>
      <!-- <a href="javascript:;" data-action="privateMessage" rel="nofollow"><%= icon("fas", "envelope") %> PM</a> -->
    </div>
  </div>
<% end %>

app/views/application/_reply_modal.html.erb
<div class="modal modal-dark fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag posts_path, method: "post" do %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="replyModalLabel">Reply to <span class="display-name">{{displayName}}</span></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="user">
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" class="profile-picture" width="50" height="50">
            <span class="display-name">{{displayName}}</span>
            <small class="username">{{username}}</small>
            &middot;
            <small class="created-at">{{createdAt}}</small>
          </div>
          <p class="original-post-content"></p>
          <div class="attachments"></div>
          <input type="hidden" name="original_post_id">
          <input type="hidden" name="original_user_id">
          <input type="hidden" name="post[type]" value="reply">
          <div class="form-group">
            <label for="message-text" class="col-form-label">Replying to <span class="username">{{username}}</span></label>
            <textarea name="post[content]" class="form-control" id="message-text" required="true"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
          <button type="submit" class="btn btn-primary">Reply</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_reply_modal_form.html.erb
<div class="modal modal-dark fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag posts_path, method: "post" do %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="replyModalLabel">Reply to <span class="display-name">{{displayName}}</span></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="user">
            <span class="display-name">{{displayName}}</span>
            <small class="username">{{username}}</small>
            &middot;
            <small class="created-at">{{createdAt}}</small>
          </div>
          <p class="original-post-content"></p>
          <input type="hidden" name="original_post_id">
          <input type="hidden" name="original_user_id">
          <input type="hidden" name="post[type]" value="reply">
          <div class="form-group">
            <label for="message-text" class="col-form-label">Replying to <span class="username">{{username}}</span></label>
            <textarea name="post[content]" class="form-control" id="message-text"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
          <button type="submit" class="btn btn-primary">Reply</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_repost_modal.html.erb
<div class="modal modal-dark fade" id="repostModal" tabindex="-1" role="dialog" aria-labelledby="repostModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag posts_path, method: "post" do %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="replyModalLabel">Repost</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="user">
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" class="profile-picture" width="50" height="50">
            <span class="display-name">{{displayName}}</span>
            <small class="username">{{username}}</small>
            &middot;
            <small class="created-at">{{createdAt}}</small>
          </div>
          <p class="original-post-content"></p>
          <div class="attachments"></div>
          <input type="hidden" name="original_post_id">
          <input type="hidden" name="original_user_id">
          <input type="hidden" name="post[repost]" value="true">
          <input type="hidden" name="post[type]" value="reply">
          <div class="form-group">
            <label for="message-text" class="col-form-label">Add message to repost (optional)</label>
            <textarea name="post[content]" class="form-control" id="message-text"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
          <button type="submit" class="btn btn-primary">Repost</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_thread_modal.html.erb
<div class="modal modal-dark fade" id="threadModal" tabindex="-1" role="dialog" aria-labelledby="threadModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag posts_path, method: "post" do %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="replyModalLabel">Thread</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="original-posts"></div>
          <div class="reply">
            <input type="hidden" name="original_post_id">
            <input type="hidden" name="original_user_id">
            <input type="hidden" name="post[type]" value="reply">
            <div class="form-group">
              <label for="message-text" class="col-form-label">Replying to <span class="username">{{username}}</span></label>
              <textarea name="post[content]" class="form-control" id="message-text" required="true"></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
          <button type="submit" class="btn btn-primary">Reply</button>
        </div>
      </div>
    <% end %>
  </div>
  <script id="thread-post-template" type="text/template">
    <div class="post">
      <div class="user">
        <a href="#">
          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" class="profile-picture" width="50" height="50">
          <span class="display-name">{{displayName}}</span>
          <small class="username">{{username}}</small>
        </a>
        <small>
          &middot;
          <a href="#" class="created-at">{{createdAt}}</a>
        </small>
      </div>
      <p class="content"></p>
      <div class="attachments"></div>
    </div>
    <hr>
  </script>
</div>

app/views/application/_user_row.html.erb
<div class="user-row">
  <div class="post-body">
    <div class="user">
      <a href="<%= user_path(username: user.username) %>">
        <% if user.profile_picture&.attached? && user.profile_picture&.variable? %>
          <%= image_tag(user.squared_profile_picture(50), class: "profile-picture") %>
        <% else %>
          <div class="profile-picture"></div>
        <% end %>
        <span class="display-name"><%= user.display_name %></span>
        <small class="username">@<%= user.username %></small>
      </a>
      <% if controller.action_name != "followers" && current_user && user&.follow?(current_user) %>
        &middot;
        <span class="badge badge-pill badge-light">follows you</span>
      <% end %>
    </div>
    <%= simple_format(html_escape(user.bio).gsub(/\@([a-zA-Z0-9_]+)/, '<a href="/u/\1">@\1</a>'), class: "bio") %>
    <div class="actions text-right">
      <% if current_user && user != current_user %>
        <% if !current_user.follow?(user) %>
          <%= link_to "Follow", follow_path(username: user.username), method: "post", remote: true, class: "btn btn-outline-primary btn-sm" %>
        <% else%>
          <%= link_to "Following", follow_path(username: user.username), method: "delete", remote: true, class: "btn btn-primary btn-sm" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>